import rtconfig
from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['BSP_USING_USBH_MOUSE']):
    src += ['usb_host_hid_mouse/app.c']
    src += ['usb_host_hid_mouse/host_mouse.c']

path = [cwd + '/usb_host_hid_mouse']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
