import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""

""")


if GetDepend(['BSP_USING_USBH_MOUSE']):
    src += ['usb_host_hid_mouse/app.c']
    src += ['usb_host_hid_mouse/host_mouse.c']
    path = [cwd + '/usb_host_hid_mouse/']


# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    CPPDEFINES = ['__START=entry']
else:
    CPPDEFINES = []
    
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
